import {
  videoGalleryIcon,
  lightBoxIcon,
  masonryVideoGridIcon,
  parallaxRowIcon,
  sliderAutoplayIcon,
  videoCarouselIcon,
  videoPlaylistIcon,
  videoSliderIcon,
  testimonialIcon,
  videoShortsReelIcon,
  videoShowcaseWallIcon,
  videoCurriculumAccordionIcon,
  videoHotspotSceneIcon,
  videoTabsGalleryIcon,
  videoScrollytellingShowcaseIcon,
  videoTimelineGalleryIcon,
  videoBentoGridIcon,
  videoComparisonGalleryIcon,
  videoJustifiedGalleryIcon,
  videoExpandingPanelsIcon,
  videoPipWallIcon,
  videoSwipeDeckIcon,
  videoMarqueeWallIcon,
  videoFlipCardsGalleryIcon,
  videoMapGalleryIcon,
  videoStoriesIcon,
  videoPodcastEpisodesIcon,
  videoPropertyTourGalleryIcon,
  videoWorkoutPlannerIcon,
  videoWeddingStoryGalleryIcon,
  videoMenuShowcaseIcon,
  videoFeatureTourIcon,
} from "../../Components/Common/utils/icons";

const siteURL = "https://bblockswp.com";
const demoLink = `${siteURL}/demo`;

export default [
  {
    name: "vgb/video-gallery",
    title: "Video Gallery",
    icon: videoGalleryIcon,
    demo: `${demoLink}/video-gallery-block-default/`,
    status: "published",
    required: true,
  },
  {
    name: "vgblk/lightbox-video-gallery",
    title: "Lightbox Video Gallery",
    icon: lightBoxIcon,
    demo: `${demoLink}/video-gallery-block-lightbox-video-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/masonry-video-grid-one",
    title: "Masonry Video Grid",
    icon: masonryVideoGridIcon,
    demo: `${demoLink}/video-gallery-block-masonry-video-grid/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/parallax-row-video-gallery",
    title: "Parallax Row Video Gallery",
    icon: parallaxRowIcon,
    demo: `${demoLink}/video-gallery-block-parallax-row-video-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/slider-autoplay-video",
    title: "Slider Autoplay Video",
    icon: sliderAutoplayIcon,
    demo: `${demoLink}/video-gallery-block-slider-autoplay-video/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-carousel-gallery",
    title: "Video Carousel Gallery",
    icon: videoCarouselIcon,
    demo: `${demoLink}/video-gallery-block-video-carousel-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-playlist-gallery",
    title: "Video Playlist Gallery",
    icon: videoPlaylistIcon,
    demo: `${demoLink}/video-gallery-block-video-playlist-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-shorts-reel",
    title: "Video Shorts Reel",
    icon: videoShortsReelIcon,
    demo: `${demoLink}/video-gallery-block-video-shorts-reel/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-showcase-wall",
    title: "Video Showcase Wall",
    icon: videoShowcaseWallIcon,
    demo: `${demoLink}/video-gallery-block-video-showcase-wall/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-slider",
    title: "Video Slider",
    icon: videoSliderIcon,
    demo: `${demoLink}/video-gallery-block-video-slider/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-testimonial-section",
    title: "Video Testimonial Section",
    icon: testimonialIcon,
    demo: `${demoLink}/video-gallery-block-video-testimonial-section/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-curriculum-accordion",
    title: "Video Curriculum Accordion",
    icon: videoCurriculumAccordionIcon,
    demo: `${demoLink}/video-gallery-block-video-curriculum-accordion/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-hotspot-scene",
    title: "Video Hotspot Scene",
    icon: videoHotspotSceneIcon,
    demo: `${demoLink}/video-gallery-block-video-hotspot-scene/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-tabs-gallery",
    title: "Video Tabs Gallery",
    icon: videoTabsGalleryIcon,
    demo: `${demoLink}/video-gallery-block-video-tabs-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-scrollytelling-showcase",
    title: "Video Scrollytelling Showcase",
    icon: videoScrollytellingShowcaseIcon,
    demo: `${demoLink}/video-gallery-block-video-scrollytelling-showcase/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-timeline-gallery",
    title: "Video Timeline Gallery",
    icon: videoTimelineGalleryIcon,
    demo: `${demoLink}/video-gallery-block-video-timeline-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-bento-grid",
    title: "Video Bento Grid",
    icon: videoBentoGridIcon,
    demo: `${demoLink}/video-gallery-block-video-bento-grid/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-comparison-gallery",
    title: "Video Comparison Gallery",
    icon: videoComparisonGalleryIcon,
    demo: `${demoLink}/video-gallery-block-video-comparison-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-justified-gallery",
    title: "Video Justified Gallery",
    icon: videoJustifiedGalleryIcon,
    demo: `${demoLink}/video-gallery-block-video-justified-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-expanding-panels",
    title: "Video Expanding Panels",
    icon: videoExpandingPanelsIcon,
    demo: `${demoLink}/video-gallery-block-video-expanding-panels/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-pip-wall",
    title: "Video Wall with Floating Player",
    icon: videoPipWallIcon,
    demo: `${demoLink}/video-gallery-block-video-wall-with-floating-player/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-swipe-deck",
    title: "Video Swipe Deck",
    icon: videoSwipeDeckIcon,
    demo: `${demoLink}/video-gallery-block-video-swipe-deck/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-marquee-wall",
    title: "Video Marquee Wall",
    icon: videoMarqueeWallIcon,
    demo: `${demoLink}/video-gallery-block-video-marquee-wall/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-flip-cards-gallery",
    title: "Video Flip Cards Gallery",
    icon: videoFlipCardsGalleryIcon,
    demo: `${demoLink}/video-gallery-block-video-flip-cards-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-map-gallery",
    title: "Video Map Gallery",
    icon: videoMapGalleryIcon,
    demo: `${demoLink}/video-gallery-block-video-map-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-stories",
    title: "Video Stories",
    icon: videoStoriesIcon,
    demo: `${demoLink}/video-gallery-block-video-stories/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-podcast-episodes",
    title: "Video Podcast Episodes",
    icon: videoPodcastEpisodesIcon,
    demo: `${demoLink}/video-gallery-block-video-podcast-episodes/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-property-tour-gallery",
    title: "Video Property Tour Gallery",
    icon: videoPropertyTourGalleryIcon,
    demo: `${demoLink}/video-gallery-block-video-property-tour-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-workout-planner",
    title: "Video Workout Planner",
    icon: videoWorkoutPlannerIcon,
    demo: `${demoLink}/video-gallery-block-video-workout-planner/#vwp-d1`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-wedding-story-gallery",
    title: "Video Wedding Story Gallery",
    icon: videoWeddingStoryGalleryIcon,
    demo: `${demoLink}/video-gallery-block-video-wedding-story-gallery/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-menu-showcase",
    title: "Video Menu Showcase",
    icon: videoMenuShowcaseIcon,
    demo: `${demoLink}/video-gallery-block-video-menu-showcase/`,
    status: "published",
    isPremium: true,
  },
  {
    name: "vgblk/video-feature-tour",
    title: "Video Feature Tour",
    icon: videoFeatureTourIcon,
    demo: `${demoLink}/video-gallery-block-video-feature-tour/#step-1`,
    status: "published",
    isPremium: true,
  },
];
